name: GameLoop
version: '1.0'
main: org.ferris.gameLoop.GameLoop
api-version: '1.21.7'

#List of commands that can be used in game.
commands:
  #The "/gameloop" command (also has the alias of "/gl").
  gameloop:
    description: "Testing"
    usage: "/gameloop <args>"
    aliases: [ gl ]
    permission: gameloop.command.gameloop
    permission-message: "You do not have permission to use this command"